definitions:
  models.Categories:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.CheckoutItem:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
    type: object
  models.CheckoutRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/models.CheckoutItem'
        type: array
    type: object
  models.Product:
    properties:
      category_id:
        type: integer
      category_name:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    type: object
  models.Report:
    properties:
      produk_terlaris:
        properties:
          nama:
            type: string
          qty_terjual:
            type: integer
        type: object
      total_revenue:
        type: number
      total_transaksi:
        type: integer
    type: object
  models.Transaction:
    properties:
      created_at:
        type: string
      details:
        items:
          $ref: '#/definitions/models.TransactionDetail'
        type: array
      id:
        type: integer
      total_amount:
        type: integer
    type: object
  models.TransactionDetail:
    properties:
      id:
        type: integer
      product_id:
        type: integer
      product_name:
        type: string
      quantity:
        type: integer
      subtotal:
        type: integer
      transaction_id:
        type: integer
    type: object
info:
  contact: {}
  description: API untuk aplikasi manajemen kasir yang di-update dengan menggunakan
    database PostgreSQL. Terdapat penambahan endpoint untuk mengelola kategori produk
    serta relasi antara produk dan kategori.
  title: Kasir API
  version: 1.0.1
paths:
  /api/checkout:
    post:
      consumes:
      - application/json
      description: 'Melakukan checkout barang: format data yang harus diisi { items:
        [ { product_id, quantity } ]}'
      parameters:
      - description: New Checkout Data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.CheckoutRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Transaction'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to create checkout
          schema:
            type: string
      summary: Checkout Product
      tags:
      - checkout
  /api/kategori:
    get:
      consumes:
      - application/json
      description: Mengambil semua data kategori produk (Challange (Optional))
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Categories'
            type: array
        "500":
          description: Failed to get categories
          schema:
            type: string
      summary: Get All Categories
      tags:
      - category
      - produk
  /api/produk:
    get:
      consumes:
      - application/json
      description: Mengambil semua data produk. Terdapat opsi untuk mendapatkan detail
        kategori produk
      parameters:
      - description: Tampilkan Detail Kategori Produk
        in: query
        name: details
        type: boolean
      - description: Tampilkan Detail Kategori Produk Berdasarkan Pencarian Nama
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "500":
          description: Failed to get products
          schema:
            type: string
      summary: Get All Products
      tags:
      - produk
    post:
      consumes:
      - application/json
      description: 'Menambahkan data produk baru, data yang perlu diisi: { category_id,
        name, price, stock }'
      parameters:
      - description: New Product Data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to create product
          schema:
            type: string
      summary: Create New Product
      tags:
      - produk
  /api/produk/{id}:
    delete:
      description: Menghapus data produk berdasarkan ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid product ID
          schema:
            type: string
        "500":
          description: Failed to delete product
          schema:
            type: string
      summary: Delete Product by ID
      tags:
      - produk
    get:
      consumes:
      - application/json
      description: Mengambil data produk berdasarkan ID. Terdapat opsi untuk mendapatkan
        detail kategori produk
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - default: false
        description: Tampilkan Detail Kategori Produk
        in: query
        name: details
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Invalid product ID
          schema:
            type: string
        "404":
          description: Product not found
          schema:
            type: string
      summary: Get Product by ID
      tags:
      - produk
    put:
      consumes:
      - application/json
      description: 'Memperbarui data produk berdasarkan ID, data yang dapat diubah:
        { category_id, name, price, stock }'
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated Product Data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to update product
          schema:
            type: string
      summary: Update Product by ID
      tags:
      - produk
  /api/report:
    get:
      consumes:
      - application/json
      description: Mengambil laporan data transaksi penjualan barang berdasarkan tanggal
        yang dipilih
      parameters:
      - description: 'Tanggal awal (Format: YYYY-MM-DD)'
        example: "2026-01-01"
        in: query
        name: start_date
        type: string
      - description: 'Tanggal akhir (Format: YYYY-MM-DD)'
        example: "2026-02-01"
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Report'
            type: array
        "500":
          description: Failed to get report
          schema:
            type: string
      summary: Get Transaction Report By Selected Date
      tags:
      - report
  /api/report/hari-ini:
    get:
      consumes:
      - application/json
      description: Mengambil laporan data transaksi penjualan barang khusus hari ini
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Report'
            type: array
        "500":
          description: Failed to get report
          schema:
            type: string
      summary: Get Today's Transaction Report
      tags:
      - report
swagger: "2.0"
