definitions:
  models.Categories:
    properties:
      harga:
        type: integer
      id:
        type: integer
      nama:
        type: string
      stok:
        type: integer
    type: object
info:
  contact: {}
  description: API sederhana untuk manajemen categories di kasir
  title: Kasir API
  version: "1.0"
paths:
  /api/categories:
    get:
      description: Mengambil semua data categories
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Categories'
            type: array
      summary: Get all Categories
  /api/categories/:
    post:
      description: Menambahkan data categories baru
      parameters:
      - description: New Categories Data
        in: body
        name: categories
        required: true
        schema:
          $ref: '#/definitions/models.Categories'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Categories'
        "400":
          description: Invalid request
          schema:
            type: string
      summary: Create new Categories
  /api/categories/{id}:
    delete:
      description: Menghapus data categories berdasarkan ID
      parameters:
      - description: Categories ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Categories berhasil dihapus
          schema:
            type: string
        "400":
          description: Invalid Categories ID
          schema:
            type: string
      summary: Delete Categories by ID
    get:
      description: Mengambil data categories berdasarkan ID
      parameters:
      - description: Categories ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Categories'
        "400":
          description: Invalid Categories ID
          schema:
            type: string
        "404":
          description: Categories tidak ditemukan
          schema:
            type: string
      summary: Get Categories by ID
    put:
      description: Memperbarui data categories berdasarkan ID
      parameters:
      - description: Categories ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated Categories Data
        in: body
        name: categories
        required: true
        schema:
          $ref: '#/definitions/models.Categories'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Categories'
        "400":
          description: Invalid request
          schema:
            type: string
      summary: Update Categories by ID
swagger: "2.0"
